services:
  - type: web
    name: spring-boot-app
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/my-spring-boot-app-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.java-buildpack/open_jdk_jre
