services:
  - type: web
    name: spring-boot-app
    env: docker
    plan: free
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: JAVA_HOME
        value: /opt/render/project/java
